services:
  - type: web
    name: business-management
    env: node
    rootDir: .
    buildCommand: npm install && npx playwright install --with-deps chromium && npm run build
    startCommand: npm run start
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    autoDeploy: true
    envVars:
