import type {
  FleetRegistryRecord,
  FleetUnitFormValues,
} from '../types/fleetRegistry.types';

const stringOrEmpty = (value?: string | null) => value ?? '';

export const createDefaultFleetUnitFormValues = (): FleetUnitFormValues => ({
  truckId: '',
  maker: '',
  model: '',
  year: '',
  plateNo: '',
  bodyNo: '',
  chassisNo: '',
  engineNo: '',
  capacity: '',
  passengerCapacity: '',
  grossWeight: '',
  netWeight: '',
  bodyType: '',
  series: '',
  classification: '',
  vehicleType: '',
  fuelType: '',
  status: 'active',
  ltoRegisterDate: '',
  orCrInfo: '',
  ownershipType: 'Company-owned',
  acquisitionDate: '',
  purchaseCost: '',
  insuranceProvider: '',
  insuranceExpiry: '',
  gpsTrackerId: '',
  depotLocation: '',
  driverAssigned: '',
  remarks: '',
});

export const recordToFleetUnitFormValues = (
  record: FleetRegistryRecord
): FleetUnitFormValues => ({
  truckId: stringOrEmpty(record.truckId),
  maker: stringOrEmpty(record.maker),
  model: stringOrEmpty(record.model),
  year: record.year ? String(record.year) : '',
  plateNo: stringOrEmpty(record.plateNo),
  bodyNo: stringOrEmpty(record.bodyNo),
  chassisNo: stringOrEmpty(record.chassisNo),
  engineNo: stringOrEmpty(record.engineNo),
  capacity: stringOrEmpty(record.capacity),
  passengerCapacity: stringOrEmpty(record.passengerCapacity),
  grossWeight: stringOrEmpty(record.grossWeight),
  netWeight: stringOrEmpty(record.netWeight),
  bodyType: stringOrEmpty(record.bodyType),
  series: stringOrEmpty(record.series),
  classification: stringOrEmpty(record.classification),
  vehicleType: stringOrEmpty(record.vehicleType),
  fuelType: stringOrEmpty(record.fuelType),
  status: record.status,
  ltoRegisterDate: stringOrEmpty(record.ltoRegisterDate),
  orCrInfo: stringOrEmpty(record.orCrInfo),
  ownershipType: record.ownershipType ?? 'Company-owned',
  acquisitionDate: stringOrEmpty(record.acquisitionDate),
  purchaseCost: stringOrEmpty(record.purchaseCost),
  insuranceProvider: stringOrEmpty(record.insuranceProvider),
  insuranceExpiry: stringOrEmpty(record.insuranceExpiry),
  gpsTrackerId: stringOrEmpty(record.gpsTrackerId),
  depotLocation: stringOrEmpty(record.depotLocation),
  driverAssigned: stringOrEmpty(record.driverAssigned),
  remarks: stringOrEmpty(record.remarks),
});
