-- Add missing bulk-related columns to products
ALTER TABLE "products"
  ADD COLUMN IF NOT EXISTS "bulkQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "bulkWeight" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "weightPerPiece" DOUBLE PRECISION NOT NULL DEFAULT 0;
