#!/usr/bin/env node
/* eslint-disable no-console */

const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding baseline test data...');

  await prisma.healthCheck.create({
    data: { status: 'ok' },
  });

  await prisma.customer.createMany({
    data: [
      {
        date: '2025-10-15',
        customerName: 'Alice Johnson',
        phoneNumber: '+1-555-0100',
        address: '123 Main St, Springfield',
        facebook: 'alice.johnson',
        emailAddress: 'alice@example.com',
        businessName: 'Alice Apparel',
        taxNumber: 'TX-ALICE-001',
        businessAddress: '123 Warehouse Ave, Springfield',
        businessContactNumber: '+1-555-0110',
        customerStatus: 'active',
      },
      {
        date: '2025-10-10',
        customerName: 'Bob Smith',
        phoneNumber: '+1-555-0200',
        address: '456 Elm St, Centerville',
        facebook: 'bob.smith',
        emailAddress: 'bob@example.com',
        businessName: 'Bob Logistics',
        taxNumber: 'TX-BOB-002',
        businessAddress: '987 Distribution Rd, Centerville',
        businessContactNumber: '+1-555-0210',
        customerStatus: 'prospect',
      },
    ],
  });

  await prisma.shipment.createMany({
    data: [
      {
        shipmentCode: 'SHIP-001',
        cvNumber: 'CV-001',
        noOfSacks: 25,
        totalCBM: 12.5,
        weight: 540,
        fee: 1500,
        shipmentStatus: 'in_transit',
        dateCreated: '2025-10-01',
        dateDelivered: null,
        duration: null,
        notes: 'Initial load for fall collection',
      },
      {
        shipmentCode: 'SHIP-002',
        cvNumber: 'CV-002',
        noOfSacks: 15,
        totalCBM: 8.2,
        weight: 320,
        fee: 900,
        shipmentStatus: 'delivered',
        dateCreated: '2025-09-15',
        dateDelivered: '2025-09-18',
        duration: '3 days',
        notes: 'Restock delivery',
      },
    ],
  });

  await prisma.transaction.createMany({
    data: [
      {
        orderDate: '2025-10-12',
        customers: 'Alice Johnson',
        productCode: 'SKU-1001',
        quantity: 12,
        unitPrice: 120,
        discount: 0,
        adjustment: 0,
        lineTotal: 1440,
        orderStatus: 'processing',
        notes: 'Priority order for launch event',
        invoiceDate: '2025-10-13',
        packedDate: null,
        shipmentCode: 'SHIP-001',
      },
      {
        orderDate: '2025-09-20',
        customers: 'Bob Smith',
        productCode: 'SKU-2040',
        quantity: 4,
        unitPrice: 260,
        discount: 10,
        adjustment: 0,
        lineTotal: 1040,
        orderStatus: 'shipped',
        notes: 'Includes promotional discount',
        invoiceDate: '2025-09-21',
        packedDate: '2025-09-22',
        shipmentCode: 'SHIP-002',
      },
      // Test data for Packing List (Prepared status, line total ≤ ₱50.00)
      {
        orderDate: '2025-10-14',
        customers: 'Alice Johnson',
        productCode: 'SKU-3001',
        quantity: 2,
        unitPrice: 20,
        discount: 0,
        adjustment: 0,
        lineTotal: 40,
        orderStatus: 'Prepared',
        notes: 'Small item for packing list test',
        invoiceDate: null,
        packedDate: null,
        shipmentCode: null,
      },
      {
        orderDate: '2025-10-14',
        customers: 'Bob Smith',
        productCode: 'SKU-3002',
        quantity: 1,
        unitPrice: 50,
        discount: 0,
        adjustment: 0,
        lineTotal: 50,
        orderStatus: 'Prepared',
        notes: 'Another item for packing list test',
        invoiceDate: null,
        packedDate: null,
        shipmentCode: null,
      },
      // Test data for Distribution (any status works)
      {
        orderDate: '2025-10-13',
        customers: 'Alice Johnson',
        productCode: 'SKU-4001',
        quantity: 5,
        unitPrice: 100,
        discount: 0,
        adjustment: 0,
        lineTotal: 500,
        orderStatus: 'processing',
        notes: 'Item for distribution test',
        invoiceDate: null,
        packedDate: null,
        shipmentCode: null,
      },
    ],
  });

  await prisma.sortingDistribution.createMany({
    data: [
      {
        productCode: 'SKU-1001',
        selectedQuantity: 12,
        rowNumber: 1,
        quantity: 50,
        percentage: 60,
        groupNumber: 'A',
        distribution: 30,
        checked: true,
      },
      {
        productCode: 'SKU-2040',
        selectedQuantity: 4,
        rowNumber: 1,
        quantity: 20,
        percentage: 40,
        groupNumber: 'B',
        distribution: 8,
        checked: false,
      },
    ],
  });

  await prisma.employee.createMany({
    data: [
      {
        employeeId: 'EMP-001',
        firstName: 'John',
        lastName: 'Doe',
        middleName: 'Michael',
        name: 'John Michael Doe',
        department: 'Sales',
        position: 'Sales Manager',
        jobTitle: 'Sales Manager',
        status: 'active',
        hireDate: '2022-01-15',
        basicSalary: 35000,
        currentSalary: 38000,
        contact: '09171234567',
        phone: '09171234567',
        email: 'john.doe@company.com',
        address: '123 Main St, Makati City, Metro Manila',
        emergencyContact: '09171234999',
        emergencyContactPerson: 'Jane Doe (Wife)',
        emergencyContactNumber: '09171234999',
        sssNumber: '34-1234567-8',
        philHealthNumber: '12-345678901-2',
        hdmfNumber: '1234-5678-9012',
        tinNumber: '123-456-789-000',
        gender: 'male',
        education: 'Bachelor of Science in Business Administration',
        dateOfBirth: '1990-05-15',
        maritalStatus: 'married',
        numberOfKids: 2,
        drivingLicense: 'N12-34-567890',
        employmentStatus: 'regular',
        employeeType: 'full-time',
        office: 'Main Office - Makati',
        hiringSource: 'LinkedIn',
        allowance: 5000,
        paymentSchedule: 'monthly',
        bankAccount: 'BDO - 1234567890',
        gcashAccount: '09171234567',
      },
      {
        employeeId: 'EMP-002',
        firstName: 'Jane',
        lastName: 'Smith',
        name: 'Jane Smith',
        department: 'Operations',
        position: 'Operations Supervisor',
        jobTitle: 'Operations Supervisor',
        status: 'active',
        hireDate: '2021-06-20',
        basicSalary: 32000,
        currentSalary: 34000,
        contact: '09181234567',
        phone: '09181234567',
        email: 'jane.smith@company.com',
        address: '456 Rizal Ave, Quezon City, Metro Manila',
        emergencyContact: '09181234888',
        emergencyContactPerson: 'Mary Smith (Mother)',
        emergencyContactNumber: '09181234888',
        sssNumber: '34-2345678-9',
        philHealthNumber: '12-456789012-3',
        hdmfNumber: '2345-6789-0123',
        tinNumber: '234-567-890-001',
        gender: 'female',
        education: 'Bachelor of Science in Industrial Engineering',
        dateOfBirth: '1992-08-22',
        maritalStatus: 'single',
        numberOfKids: 0,
        drivingLicense: 'N23-45-678901',
        employmentStatus: 'regular',
        employeeType: 'full-time',
        office: 'Warehouse - Paranaque',
        hiringSource: 'Employee Referral',
        allowance: 4000,
        paymentSchedule: 'monthly',
        bankAccount: 'BPI - 2345678901',
      },
      {
        employeeId: 'EMP-003',
        firstName: 'Mike',
        lastName: 'Johnson',
        middleName: 'Andrew',
        name: 'Mike Andrew Johnson',
        department: 'Warehouse',
        position: 'Warehouse Staff',
        jobTitle: 'Warehouse Staff',
        status: 'on-leave',
        hireDate: '2023-03-10',
        basicSalary: 18000,
        currentSalary: 18000,
        contact: '09191234567',
        phone: '09191234567',
        email: 'mike.johnson@company.com',
        address: '789 Commonwealth Ave, Quezon City',
        emergencyContact: '09191234777',
        emergencyContactPerson: 'Linda Johnson (Sister)',
        emergencyContactNumber: '09191234777',
        sssNumber: '34-3456789-0',
        philHealthNumber: '12-567890123-4',
        hdmfNumber: '3456-7890-1234',
        tinNumber: '345-678-901-002',
        gender: 'male',
        education: 'High School Graduate',
        dateOfBirth: '1995-12-03',
        maritalStatus: 'single',
        drivingLicense: 'N34-56-789012',
        employmentStatus: 'probationary',
        employeeType: 'full-time',
        office: 'Warehouse - Paranaque',
        hiringSource: 'Walk-in',
        allowance: 2000,
        paymentSchedule: 'semi-monthly',
        gcashAccount: '09191234567',
      },
      {
        employeeId: 'EMP-004',
        firstName: 'Sarah',
        lastName: 'Williams',
        middleName: 'Grace',
        name: 'Sarah Grace Williams',
        department: 'Accounting',
        position: 'Accountant',
        jobTitle: 'Accountant',
        status: 'active',
        hireDate: '2020-09-05',
        basicSalary: 28000,
        currentSalary: 32000,
        contact: '09201234567',
        phone: '09201234567',
        email: 'sarah.williams@company.com',
        address: '321 Ortigas Ave, Pasig City, Metro Manila',
        emergencyContact: '09201234666',
        emergencyContactPerson: 'David Williams (Husband)',
        emergencyContactNumber: '09201234666',
        sssNumber: '34-4567890-1',
        philHealthNumber: '12-678901234-5',
        hdmfNumber: '4567-8901-2345',
        tinNumber: '456-789-012-003',
        gender: 'female',
        education: 'Bachelor of Science in Accountancy',
        dateOfBirth: '1988-04-18',
        maritalStatus: 'married',
        numberOfKids: 1,
        drivingLicense: 'N45-67-890123',
        employmentStatus: 'regular',
        employeeType: 'full-time',
        office: 'Main Office - Makati',
        hiringSource: 'JobStreet',
        allowance: 3500,
        paymentSchedule: 'monthly',
        bankAccount: 'Metrobank - 3456789012',
      },
      {
        employeeId: 'EMP-005',
        firstName: 'Robert',
        lastName: 'Brown',
        name: 'Robert Brown',
        department: 'Drivers',
        position: 'Delivery Driver',
        jobTitle: 'Delivery Driver',
        status: 'inactive',
        hireDate: '2019-11-12',
        basicSalary: 22000,
        currentSalary: 24000,
        contact: '09211234567',
        phone: '09211234567',
        email: 'robert.brown@company.com',
        address: '654 EDSA, Mandaluyong City, Metro Manila',
        emergencyContact: '09211234555',
        emergencyContactPerson: 'Betty Brown (Mother)',
        emergencyContactNumber: '09211234555',
        sssNumber: '34-5678901-2',
        philHealthNumber: '12-789012345-6',
        hdmfNumber: '5678-9012-3456',
        tinNumber: '567-890-123-004',
        gender: 'male',
        education: 'Vocational Course - Automotive',
        dateOfBirth: '1985-09-28',
        maritalStatus: 'divorced',
        numberOfKids: 1,
        drivingLicense: 'P123-45-678901 (Professional)',
        employmentStatus: 'regular',
        employeeType: 'full-time',
        office: 'Warehouse - Paranaque',
        hiringSource: 'Facebook Jobs',
        allowance: 3000,
        paymentSchedule: 'weekly',
        bankAccount: 'Landbank - 4567890123',
      },
    ],
  });

  console.log('✅ Test data seeded.');
}

main()
  .catch((error) => {
    console.error('❌ Failed to seed database:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
