import { z } from 'zod';

export const productDataSchema = z.object({
  'Shipment Code': z.string().max(100).nullable(),
  'CV Number': z.string().max(191).nullable(),
  'No. Of Sacks': z.number().min(0),
  'Total CBM': z.number().min(0),
  Weight: z.number().min(0),
  'Shipment Status': z.string().max(191).nullable(),
  'Posting Date': z.string().nullable(),
  'Order Date': z.string().nullable(),
  Payment: z.string().max(191).nullable(),
  'Payment Method': z.string().max(100).nullable().optional(),
  'Payment Card Id': z.string().max(191).nullable().optional(),
  Product: z.string().max(191).nullable(),
  'Product Code': z.string().min(1).max(191),
  'Age Range': z.string().max(191).nullable(),
  Unit: z.string().max(50).nullable(),
  'Unit Price': z.number().min(0),
  Quantity: z.number().min(0),
  'Alibaba Shipping Cost': z.number().min(0),
  'Exchange Rates': z.number().min(0),
  PHP: z.number().min(0),
  'Sub Total (PHP)': z.number().min(0),
  'Transaction Fee': z.number().min(0),
  'Grand Total': z.number().min(0),
  "Forwarder's Fee": z.number().min(0),
  Lalamove: z.number().min(0),
  'Packaging Cost': z.number().min(0),
  'Suggested Price': z.number().min(0),
  'Actual Price': z.number().min(0),
  'Base Price': z.number().min(0),
  COGS: z.number().min(0),
  'Projected Sales': z.number().min(0),
  'Projected Profit': z.number().min(0),
  'Projected Profit (%)': z.number(),
  'Total Markup': z.number(),
  'Link To Post': z.string().max(500).nullable(),
  'Bulk Quantity': z.number().min(0),
  'Bulk Weight': z.number().min(0),
  'Weight Per Piece': z.number().min(0),
});

export const productArraySchema = z.array(productDataSchema).min(1);
