#!/usr/bin/env tsx
/**
 * Float → Decimal monetary migration analysis.
 *
 * Reads `prisma/schema.prisma` and produces:
 *   1. The list of every `Float` field that *appears* to be monetary
 *      (heuristic: name contains price/cost/total/amount/fee/balance/
 *      payment/discount/grand/subtotal/cogs/wage/rate/cash/credit/debit).
 *   2. A grep-style scan of `src/**` for arithmetic on any of those
 *      Prisma model fields, flagging callsites that would need to switch
 *      to `Decimal.add`/`mul`/etc instead of native `+`/`*`.
 *   3. A markdown report at
 *      `docs/reports/FLOAT_TO_DECIMAL_MIGRATION_ANALYSIS.md`.
 *
 * IMPORTANT: This script is *analysis only*. It does NOT modify the
 * schema or any TypeScript source. The migration itself is high-risk
 * (data conversion + every arithmetic call site + Prisma.Decimal vs
 * number type drift) and is tracked in IMPROVEMENTS_CHECKLIST.md (§1).
 *
 * Usage:
 *   npx tsx scripts/analyze-float-to-decimal.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const REPO_ROOT = path.resolve(__dirname, '..');
const SCHEMA_PATH = path.join(REPO_ROOT, 'prisma', 'schema.prisma');
const SRC_DIR = path.join(REPO_ROOT, 'src');
const OUT_PATH = path.join(
  REPO_ROOT,
  'docs',
  'reports',
  'FLOAT_TO_DECIMAL_MIGRATION_ANALYSIS.md'
);

const MONETARY_HINTS = [
  'price',
  'cost',
  'total',
  'amount',
  'fee',
  'balance',
  'payment',
  'discount',
  'grand',
  'subtotal',
  'cogs',
  'wage',
  'rate',
  'cash',
  'credit',
  'debit',
  'allowance',
  'income',
  'expense',
  'refund',
  'tax',
  'commission',
  'salary',
];

interface FloatField {
  model: string;
  field: string;
  isMonetary: boolean;
}

function parseFloatFields(schemaSrc: string): FloatField[] {
  const fields: FloatField[] = [];
  const modelRegex = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  let m: RegExpExecArray | null;
  while ((m = modelRegex.exec(schemaSrc)) !== null) {
    const modelName = m[1];
    const body = m[2];
    const lineRegex = /^\s*(\w+)\s+Float(\?|\s|\[)/gm;
    let lm: RegExpExecArray | null;
    while ((lm = lineRegex.exec(body)) !== null) {
      const fieldName = lm[1];
      const lower = fieldName.toLowerCase();
      const isMonetary = MONETARY_HINTS.some((hint) => lower.includes(hint));
      fields.push({ model: modelName, field: fieldName, isMonetary });
    }
  }
  return fields;
}

function walkTs(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) {
      continue;
    }
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkTs(full));
    } else if (/\.(ts|tsx)$/.test(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

interface Hit {
  file: string;
  line: number;
  field: string;
  snippet: string;
}

function scanArithmeticUsages(monetaryFields: string[]): Hit[] {
  const hits: Hit[] = [];
  // Heuristic: lines mentioning a monetary field name AND containing one of
  // the arithmetic operators (`+`, `-`, `*`, `/`, `+=`, `-=`, etc) other
  // than simple property assignment from a single source.
  const arithRe = /[+\-*/]=?|Math\.(round|floor|ceil|abs)/;
  const fieldSet = monetaryFields;
  for (const file of walkTs(SRC_DIR)) {
    let content: string;
    try {
      content = fs.readFileSync(file, 'utf8');
    } catch {
      continue;
    }
    const lines = content.split('\n');
    lines.forEach((line, idx) => {
      if (!arithRe.test(line)) {
        return;
      }
      for (let fi = 0; fi < fieldSet.length; fi++) {
        const field = fieldSet[fi];
        // Look for `.field` accesses or destructured `field` references.
        const re = new RegExp(`\\b${field}\\b`);
        if (re.test(line)) {
          hits.push({
            file: path.relative(REPO_ROOT, file),
            line: idx + 1,
            field,
            snippet: line.trim().slice(0, 200),
          });
          break;
        }
      }
    });
  }
  return hits;
}

function main(): void {
  const schemaSrc = fs.readFileSync(SCHEMA_PATH, 'utf8');
  const allFields = parseFloatFields(schemaSrc);
  const monetary = allFields.filter((f) => f.isMonetary);
  const monetaryFieldNames = Array.from(new Set(monetary.map((f) => f.field)));

  // eslint-disable-next-line no-console
  console.log(
    `[analyze-float-to-decimal] Found ${allFields.length} Float fields total, ${monetary.length} flagged monetary across ${
      new Set(monetary.map((f) => f.model)).size
    } models.`
  );

  const hits = scanArithmeticUsages(monetaryFieldNames);

  const lines: string[] = [];
  lines.push('# Float → Decimal Migration Analysis');
  lines.push('');
  lines.push(
    `Generated by \`scripts/analyze-float-to-decimal.ts\` on ${new Date().toISOString()}.`
  );
  lines.push('');
  lines.push('## 1. Monetary Float fields in schema');
  lines.push('');
  lines.push('| Model | Field |');
  lines.push('|-------|-------|');
  for (const f of monetary) {
    lines.push(`| \`${f.model}\` | \`${f.field}\` |`);
  }
  lines.push('');
  lines.push(`**Total monetary Float fields:** ${monetary.length}`);
  lines.push('');
  lines.push('## 2. Non-monetary Float fields (likely fine to leave)');
  lines.push('');
  const nonMon = allFields.filter((f) => !f.isMonetary);
  lines.push('| Model | Field |');
  lines.push('|-------|-------|');
  for (const f of nonMon) {
    lines.push(`| \`${f.model}\` | \`${f.field}\` |`);
  }
  lines.push('');
  lines.push('## 3. Source-code arithmetic on monetary field names');
  lines.push('');
  lines.push(
    '> Heuristic match — a line is flagged when it both references a monetary field name and contains an arithmetic operator. Manual review is required; expect false positives (e.g. comparisons, schema/migration code, comment lines).'
  );
  lines.push('');
  lines.push(`**Flagged callsites:** ${hits.length}`);
  lines.push('');
  lines.push('| File | Line | Field | Snippet |');
  lines.push('|------|------|-------|---------|');
  for (const h of hits.slice(0, 500)) {
    const safe = h.snippet.replace(/\|/g, '\\|');
    lines.push(`| \`${h.file}\` | ${h.line} | \`${h.field}\` | \`${safe}\` |`);
  }
  if (hits.length > 500) {
    lines.push('');
    lines.push(`(${hits.length - 500} additional rows truncated.)`);
  }
  lines.push('');
  lines.push('## 4. Migration plan (recommended phasing)');
  lines.push('');
  lines.push(
    '1. **Pick one model** with the smallest call-site footprint (use the table above to count).'
  );
  lines.push(
    '2. **Add a parallel Decimal column** alongside the Float column; backfill via a one-shot script that reads existing rows.'
  );
  lines.push(
    '3. **Update writers first** — make every code path that writes the Float field also write the Decimal field. Validate with integration tests.'
  );
  lines.push(
    '4. **Update readers** — switch consumers to the Decimal column. Use `Prisma.Decimal` arithmetic helpers; never coerce to `Number` for math.'
  );
  lines.push(
    '5. **Drop the Float column** in a follow-up migration once readers are stable for at least one release.'
  );
  lines.push(
    '6. **Repeat** per model. Do not attempt a big-bang migration across all 30+ fields at once.'
  );
  lines.push('');
  lines.push('## 5. Risks');
  lines.push('');
  lines.push(
    '- **Type drift**: TypeScript treats `Prisma.Decimal` and `number` as incompatible; expect cascading type errors at every callsite.'
  );
  lines.push(
    '- **Serialization**: `Decimal` does not JSON-serialize natively; API responses need explicit `.toString()` or a custom serializer.'
  );
  lines.push(
    '- **Inventory & ledger invariants**: any rounding change can shift balances by ±1 centavo. Double-entry assertions must be re-verified on real seed data after each model migration.'
  );
  lines.push(
    '- **Frontend math**: charts and totals computed in the browser also need Decimal-equivalent libraries (e.g. `decimal.js`).'
  );

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, lines.join('\n') + '\n', 'utf8');
  // eslint-disable-next-line no-console
  console.log(
    `[analyze-float-to-decimal] Wrote report: ${path.relative(REPO_ROOT, OUT_PATH)}`
  );
}

main();
