import type { EmployeeAutomationExecutionResult } from './types';

const TIME_PATTERN = /^([01]\d|2[0-3]):[0-5]\d$/;
const MINUTES_PER_DAY = 24 * 60;

type SkipReason = 'already-recorded' | 'on-leave' | 'no-schedule';

const SKIP_REASON_LABEL: Record<SkipReason, string> = {
  'already-recorded': 'already recorded',
  'on-leave': 'on approved leave',
  'no-schedule': 'no schedule on file',
};

export interface StayInAutomationDomainEmployee {
  employeeId: string;
  employeeName: string;
  department: string;
  position: string;
}

export interface StayInAutomationScheduleSnapshot {
  employeeId: string;
  startTime: string | null;
  endTime: string | null;
  department: string | null;
  position: string | null;
}

export interface StayInAutomationAttendancePayload {
  employeeId: string;
  employeeName: string;
  department: string;
  position: string;
  date: string;
  timeIn: string;
  timeOut: string;
  break1Start: string | null;
  break1End: string | null;
  lunchStart: string | null;
  lunchEnd: string | null;
  break2Start: string | null;
  break2End: string | null;
  totalHours: number;
  status: 'present';
  details: string;
  notes: string;
}

export interface StayInAutomationClients {
  loadEmployees(): Promise<StayInAutomationDomainEmployee[]>;
  loadExistingAttendance(
    employeeIds: string[],
    targetDate: string
  ): Promise<string[]>;
  loadScheduleSnapshots(
    employeeIds: string[],
    targetDate: string
  ): Promise<StayInAutomationScheduleSnapshot[]>;
  loadApprovedLeaves(
    employeeIds: string[],
    targetDate: string
  ): Promise<string[]>;
  createAttendanceRecords(
    payloads: StayInAutomationAttendancePayload[]
  ): Promise<number>;
}

const parseTimeToMinutes = (
  value: string | null | undefined
): number | null => {
  if (!value || !TIME_PATTERN.test(value)) {
    return null;
  }

  const [hour, minute] = value.split(':').map(Number);
  if (Number.isNaN(hour) || Number.isNaN(minute)) {
    return null;
  }

  return hour * 60 + minute;
};

const normaliseTime = (
  value: string | null | undefined,
  fallback: string
): string => {
  if (value && TIME_PATTERN.test(value)) {
    return value;
  }

  if (TIME_PATTERN.test(fallback)) {
    return fallback;
  }

  return '00:00';
};

const calculateDurationHours = (start: string, end: string): number => {
  const startMinutes = parseTimeToMinutes(start);
  const endMinutes = parseTimeToMinutes(end);

  if (startMinutes === null || endMinutes === null) {
    return 0;
  }

  const rawDiff =
    endMinutes <= startMinutes
      ? endMinutes + MINUTES_PER_DAY - startMinutes
      : endMinutes - startMinutes;

  return Math.max(0, Math.round((rawDiff / 60) * 100) / 100);
};

const groupSchedulesByEmployee = (
  snapshots: StayInAutomationScheduleSnapshot[]
) =>
  snapshots.reduce<Map<string, StayInAutomationScheduleSnapshot[]>>(
    (acc, snapshot) => {
      const list = acc.get(snapshot.employeeId) ?? [];
      list.push(snapshot);
      acc.set(snapshot.employeeId, list);
      return acc;
    },
    new Map()
  );

function buildAttendancePayload(
  employee: StayInAutomationDomainEmployee,
  targetDate: string,
  runTimestamp: string,
  timezone: string,
  defaultTime: string,
  scheduleEntries: StayInAutomationScheduleSnapshot[]
): StayInAutomationAttendancePayload {
  const sortedSchedules = [...scheduleEntries].sort((a, b) => {
    const aStart = parseTimeToMinutes(a.startTime);
    const bStart = parseTimeToMinutes(b.startTime);

    if (aStart === null && bStart === null) {
      return 0;
    }
    if (aStart === null) {
      return 1;
    }
    if (bStart === null) {
      return -1;
    }
    return aStart - bStart;
  });

  const firstSchedule = sortedSchedules[0];
  const lastSchedule = sortedSchedules[sortedSchedules.length - 1];

  const timeIn = normaliseTime(firstSchedule?.startTime ?? null, defaultTime);
  const timeOutCandidate = normaliseTime(lastSchedule?.endTime ?? null, timeIn);
  const timeOut = timeOutCandidate || timeIn;
  const totalHours = calculateDurationHours(timeIn, timeOut);

  const department =
    firstSchedule?.department ??
    employee.department ??
    scheduleEntries[0]?.department ??
    '';
  const position =
    firstSchedule?.position ??
    employee.position ??
    scheduleEntries[0]?.position ??
    '';

  return {
    employeeId: employee.employeeId,
    employeeName: employee.employeeName,
    department,
    position,
    date: targetDate,
    timeIn,
    timeOut,
    break1Start: null,
    break1End: null,
    lunchStart: null,
    lunchEnd: null,
    break2Start: null,
    break2End: null,
    totalHours,
    status: 'present',
    details: 'Auto-recorded stay-in presence entry.',
    notes: `Generated by stay-in automation on ${runTimestamp} (${timezone}).`,
  };
}

export async function runSharedStayInAutoPresence(params: {
  clients: StayInAutomationClients;
  targetDate: string;
  runTimestamp: string;
  timezone: string;
  defaultTime: string;
}): Promise<EmployeeAutomationExecutionResult> {
  const employees = await params.clients.loadEmployees();

  if (employees.length === 0) {
    return {
      automationType: 'stay-in-attendance',
      status: 'skipped',
      message: 'No stay-in employees found to process.',
      processed: 0,
      inserted: 0,
      skipped: 0,
      targetDate: params.targetDate,
      periodKey: params.targetDate,
    };
  }

  const employeeIds = employees.map((employee) => employee.employeeId);
  const [existingAttendanceIds, scheduleSnapshots, approvedLeaveIds] =
    await Promise.all([
      params.clients.loadExistingAttendance(employeeIds, params.targetDate),
      params.clients.loadScheduleSnapshots(employeeIds, params.targetDate),
      params.clients.loadApprovedLeaves(employeeIds, params.targetDate),
    ]);

  const existingAttendanceSet = new Set(existingAttendanceIds);
  const schedulesByEmployee = groupSchedulesByEmployee(scheduleSnapshots);
  const onLeaveSet = new Set(approvedLeaveIds);

  const skippedDetails: Array<{ employeeId: string; reason: SkipReason }> = [];
  const recordsToCreate: StayInAutomationAttendancePayload[] = [];

  for (const employee of employees) {
    if (existingAttendanceSet.has(employee.employeeId)) {
      skippedDetails.push({
        employeeId: employee.employeeId,
        reason: 'already-recorded',
      });
      continue;
    }

    if (onLeaveSet.has(employee.employeeId)) {
      skippedDetails.push({
        employeeId: employee.employeeId,
        reason: 'on-leave',
      });
      continue;
    }

    const employeeSchedules =
      schedulesByEmployee.get(employee.employeeId) ?? [];
    if (employeeSchedules.length === 0) {
      skippedDetails.push({
        employeeId: employee.employeeId,
        reason: 'no-schedule',
      });
      continue;
    }

    recordsToCreate.push(
      buildAttendancePayload(
        employee,
        params.targetDate,
        params.runTimestamp,
        params.timezone,
        params.defaultTime,
        employeeSchedules
      )
    );
  }

  const inserted = recordsToCreate.length
    ? await params.clients.createAttendanceRecords(recordsToCreate)
    : 0;
  const processed = employees.length;
  const skipped = processed - inserted;

  const skippedSummary = skippedDetails.length
    ? (() => {
        const counts = skippedDetails.reduce<Map<SkipReason, number>>(
          (acc, detail) =>
            acc.set(detail.reason, (acc.get(detail.reason) ?? 0) + 1),
          new Map()
        );

        return Array.from(counts.entries())
          .map(([reason, count]) => `${count} ${SKIP_REASON_LABEL[reason]}`)
          .join(', ');
      })()
    : '';

  const message =
    inserted > 0
      ? `Auto-recorded stay-in attendance for ${params.targetDate}: ${inserted} recorded, ${skipped} skipped.${skippedSummary ? ` Skipped reasons: ${skippedSummary}.` : ''}`
      : `No attendance entries created for ${params.targetDate}. ${skipped} employee(s) skipped.${skippedSummary ? ` Reasons: ${skippedSummary}.` : ''}`;

  return {
    automationType: 'stay-in-attendance',
    status: inserted > 0 ? 'success' : 'skipped',
    message,
    processed,
    inserted,
    skipped,
    targetDate: params.targetDate,
    periodKey: params.targetDate,
  };
}
