export const householdExpenseCategoryOptions = [
  'Debt Payments',
  'Education',
  'Entertainment',
  'Excercise',
  'Food',
  'Food - Grab',
  'Food - Panda',
  'Gifts & Donations',
  'Groceries',
  'Healthcare',
  'Home',
  'Household Supplies',
  'House Rent',
  'Housing',
  'Insurance',
  'Loans/Payables',
  'Miscellaneous',
  'Personal Care',
  'Pets',
  'Restaurants',
  'Savings & Investments',
  'School Supplies',
  'Shopping',
  'Subsciptions',
  'Transportation',
  'Transportation - Grab Car',
  'Travel',
  'Utilities - Electricity',
  'Utilities - Internet',
  'Utilities - Water',
  "Workers' - others",
  "Workers' Salary",
] as const;
