export const householdExpenseCategoryOptions = [
  'Groceries',
  'Utilities',
  'Housing',
  'Transportation',
  'Insurance',
  'Healthcare',
  'Debt Payments',
  'Education',
  'Savings & Investments',
  'Personal Care',
  'Entertainment',
  'Gifts & Donations',
  'Pets',
  'Household Supplies',
  'Childcare',
  'Travel',
  'Miscellaneous',
] as const;
